export interface DictCategoryConfig {
  id: string
  name: string
  emoji: string
  group: 'Animals' | 'Plants' | 'Food & Drink' | 'Things & Tools' | 'Science & Nature' | 'People & Activities'
  keywords: string[]
  roots: string[]
  excludeRoots?: string[]
  maxDepth?: number
  minWords?: number
  allowCapitalized?: boolean
  denyTokens?: string[]
  manualDeny?: { token: string; reason: string }[]
}

export const DICT_VERSION = 'oewn2025-scowl2020-1'

const deny = (token: string, reason: string) => ({ token, reason })

export const GLOBAL_EXCLUDE_ROOTS = [
  '04572661-n', // weapon
  '03252323-n', // drug
  '03814104-n', // narcotic
  '07900542-n', // alcoholic drink
  '04449965-n', // tobacco product
  '12928225-n', // tobacco plant
  '05521732-n', // intimate anatomy
  '03417816-n', // execution device
  '03348699-n', // firearm
  '03309675-n', // explosive
  '02869918-n', // bomb
]

export const GLOBAL_DENY_TOKENS = [
  'ALE',
  'AMMO',
  'BOMB',
  'BRANDY',
  'BREAST',
  'BULLET',
  'CANNABIS',
  'CIGAR',
  'CIGARETTE',
  'COCAINE',
  'COCKTAIL',
  'CROTCH',
  'DAGGER',
  'GIN',
  'GROIN',
  'GUN',
  'HEROIN',
  'KNIFE',
  'LIQUOR',
  'MORPHINE',
  'OPIUM',
  'PISTOL',
  'RIFLE',
  'RUM',
  'SWORD',
  'TOBACCO',
  'UTERUS',
  'VODKA',
  'WHISKEY',
  'WINE',
]

export const CATEGORY_CONFIGS: DictCategoryConfig[] = [
  {
    id: 'mammals',
    name: 'Mammals',
    emoji: '🐻',
    group: 'Animals',
    keywords: ['animal', 'mammal', 'wildlife'],
    roots: ['01864419-n'],
    maxDepth: 8,
    denyTokens: ['BEEF', 'ENTIRE', 'HUMAN', 'HUMANS', 'LIVESTOCK', 'MANKIND', 'MOUNT'],
    manualDeny: [
      deny('CUR', 'derogatory common meaning'),
      deny('MILKER', 'dated occupational animal term'),
      deny('PLACENTAL', 'technical adjective, not animal name'),
      deny('FLYINGCAT', 'obscure/bizarre common name'),
      deny('OTTERSHREW', 'obscure classroom fit'),
      deny('SANDRAT', 'obscure classroom fit'),
      deny('BEAVERRAT', 'obscure classroom fit'),
      deny('TRADERAT', 'bizarre classroom fit'),
      deny('COACHDOG', 'generic dog compound'),
      deny('HUNTINGDOG', 'generic dog compound'),
      deny('GUARDDOG', 'generic dog compound'),
      deny('GUIDEDOG', 'generic dog compound'),
      deny('HEARINGDOG', 'generic dog compound'),
      deny('POLICEDOG', 'generic dog compound'),
      deny('SPORTINGDOG', 'generic dog compound'),
      deny('WORKINGDOG', 'generic dog compound'),
      deny('STABLECOMPANION', 'bizarre/dated animal term'),
      deny('MODERNMAN', 'human ancestry term, not worksheet animal'),
      deny('ATTACKDOG', 'violent connotation'),
      deny('MONKEYDOG', 'bizarre classroom fit'),
      deny('SAUSAGEDOG', 'informal/odd breed nickname'),
      deny('SAUSAGEHOUND', 'informal/odd breed nickname'),
      deny('GUNDOG', 'weapon/hunting association'),
      deny('FALSEVAMPIRE', 'scary common name'),
      deny('DOMESTICASS', 'contains classroom-inappropriate word'),
      deny('WILDASS', 'contains classroom-inappropriate word'),
      deny('LIVERCHESTNUT', 'color term, not mammal name'),
    ],
  },
  {
    id: 'dog-breeds',
    name: 'Dog breeds',
    emoji: '🐶',
    group: 'Animals',
    keywords: ['dog', 'breed', 'pet'],
    roots: ['02086723-n'],
    maxDepth: 7,
    allowCapitalized: true,
    denyTokens: [
      'BARKER',
      'BADGERDOG',
      'BOWWOW',
      'CARDIGAN',
      'CARRIAGEDOG',
      'COACHDOG',
      'CUR',
      'DOGGY',
      'DOMESTICDOG',
      'GAZELLEHOUND',
      'GUNDOG',
      'ATTACKDOG',
      'GUARDDOG',
      'GUIDEDOG',
      'HEARINGDOG',
      'HOUNDDOG',
      'HUNTINGDOG',
      'MUTT',
      'POOCH',
      'POLICEDOG',
      'PUPPY',
      'SAUSAGEDOG',
      'SAUSAGEHOUND',
      'SHEEPDOG',
      'SHEPHERDDOG',
      'SLEDDOG',
      'SPORTINGDOG',
      'TOY',
      'TOYDOG',
      'WATCHDOG',
      'WORKINGDOG',
      'MONKEYDOG',
    ],
  },
  {
    id: 'cats',
    name: 'Cats',
    emoji: '🐱',
    group: 'Animals',
    keywords: ['cat', 'feline', 'wildcat'],
    roots: ['02123649-n'],
    maxDepth: 7,
    manualDeny: [
      deny('CHICK', 'slang/common non-bird meaning'),
      deny('TITMOUSE', 'contains crude slang token'),
      deny('BLUETIT', 'contains crude slang token'),
      deny('BUSHTIT', 'contains crude slang token'),
      deny('BANANAQUIT', 'obscure classroom fit'),
      deny('STAKEDRIVER', 'obscure folk name'),
      deny('REEVE', 'obscure classroom fit'),
    ],
  },
  {
    id: 'birds',
    name: 'Birds',
    emoji: '🐦',
    group: 'Animals',
    keywords: ['bird', 'avian', 'feather'],
    roots: ['01505702-n'],
    maxDepth: 7,
  },
  {
    id: 'birds-of-prey',
    name: 'Birds of prey',
    emoji: '🦅',
    group: 'Animals',
    keywords: ['raptor', 'eagle', 'hawk', 'owl'],
    roots: ['01606971-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'fish',
    name: 'Fish',
    emoji: '🐟',
    group: 'Animals',
    keywords: ['fish', 'aquatic', 'ocean'],
    roots: ['02514684-n'],
    maxDepth: 7,
    manualDeny: [
      deny('HIND', 'not fish in common classroom use'),
      deny('GRUBBY', 'not fish in common classroom use'),
      deny('RASHER', 'not fish in common classroom use'),
      deny('BLUEPOINTED', 'bizarre/unclear name'),
      deny('SAILORSCHOICE', 'obscure classroom fit'),
      deny('FISHDOCTOR', 'bizarre classroom fit'),
      deny('HORNEDWHIFF', 'obscure classroom fit'),
      deny('MADEMOISELLE', 'obscure classroom fit'),
      deny('SEAPOACHER', 'violent/crime connotation'),
    ],
  },
  {
    id: 'reptiles',
    name: 'Reptiles',
    emoji: '🦎',
    group: 'Animals',
    keywords: ['reptile', 'scales', 'cold-blooded'],
    roots: ['01663732-n'],
    maxDepth: 7,
    manualDeny: [
      deny('HOOPSNAKE', 'folklore animal, not science fit'),
      deny('THUNDERSNAKE', 'folklore/obscure animal name'),
      deny('VENOMOUSLIZARD', 'generic danger-focused term'),
    ],
  },
  {
    id: 'snakes',
    name: 'Snakes',
    emoji: '🐍',
    group: 'Animals',
    keywords: ['snake', 'serpent', 'reptile'],
    roots: ['01729333-n'],
    maxDepth: 7,
  },
  {
    id: 'lizards',
    name: 'Lizards',
    emoji: '🦎',
    group: 'Animals',
    keywords: ['lizard', 'reptile', 'gecko'],
    roots: ['01677105-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'amphibians',
    name: 'Amphibians',
    emoji: '🐸',
    group: 'Animals',
    keywords: ['frog', 'toad', 'newt'],
    roots: ['01630065-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'insects',
    name: 'Insects',
    emoji: '🐞',
    group: 'Animals',
    keywords: ['insect', 'bug', 'arthropod'],
    roots: ['02162607-n'],
    maxDepth: 7,
    manualDeny: [
      deny('CRABLOUSE', 'pubic-louse association'),
      deny('ORIENTALROACH', 'dated/offensive geographic term'),
      deny('COTTONSTRAIN', 'not common insect name'),
      deny('COOTIE', 'teasing/slang connotation'),
    ],
  },
  {
    id: 'butterflies-moths',
    name: 'Butterflies & moths',
    emoji: '🦋',
    group: 'Animals',
    keywords: ['butterfly', 'moth', 'insect'],
    roots: ['02276911-n', '02285853-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'spiders-arachnids',
    name: 'Spiders & arachnids',
    emoji: '🕷️',
    group: 'Animals',
    keywords: ['spider', 'arachnid', 'scorpion'],
    roots: ['01771988-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'crustaceans-shellfish',
    name: 'Crustaceans & shellfish',
    emoji: '🦀',
    group: 'Animals',
    keywords: ['crab', 'lobster', 'mollusk', 'shellfish'],
    roots: ['01977414-n', '01943377-n'],
    maxDepth: 7,
    minWords: 10,
    manualDeny: [
      deny('BLEEDINGTOOTH', 'morbid and not shellfish'),
      deny('WHALELOUSE', 'parasite name, poor classroom fit'),
      deny('SEALOUSE', 'parasite name, poor classroom fit'),
      deny('FISHLOUSE', 'parasite name, poor classroom fit'),
      deny('BEACHFLEA', 'flea/parasite connotation'),
    ],
  },
  {
    id: 'dinosaurs',
    name: 'Dinosaurs',
    emoji: '🦖',
    group: 'Animals',
    keywords: ['dinosaur', 'prehistoric', 'fossil'],
    roots: ['01702472-n'],
    maxDepth: 8,
    minWords: 8,
  },
  {
    id: 'trees',
    name: 'Trees',
    emoji: '🌳',
    group: 'Plants',
    keywords: ['tree', 'forest', 'wood'],
    roots: ['13124818-n'],
    maxDepth: 7,
    manualDeny: [
      deny('SAMBA', 'not tree in common classroom use'),
      deny('LAWYERCANE', 'bizarre/common non-tree phrase'),
      deny('OPOSSUMWOOD', 'obscure classroom fit'),
      deny('MARMALADEBOX', 'obscure classroom fit'),
      deny('PUDDINGBERRY', 'obscure classroom fit'),
      deny('SACREDFIG', 'religious wording'),
    ],
  },
  {
    id: 'flowers',
    name: 'Flowers',
    emoji: '🌸',
    group: 'Plants',
    keywords: ['flower', 'bloom', 'garden'],
    roots: ['11690372-n'],
    maxDepth: 7,
    manualDeny: [
      deny('CHATTERBOX', 'common non-flower meaning'),
      deny('BLOOMER', 'clothing/slang connotation'),
      deny('MOURNFULWIDOW', 'morbid/dating connotation'),
      deny('MEETINGHOUSE', 'not flower in common use'),
      deny('TONGHO', 'obscure classroom fit'),
      deny('SCORPIONWEED', 'unfriendly/scary common name'),
    ],
  },
  {
    id: 'herbs-spices',
    name: 'Herbs & spices',
    emoji: '🌿',
    group: 'Plants',
    keywords: ['herb', 'spice', 'seasoning'],
    roots: ['07827392-n', '07828160-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'fruits',
    name: 'Fruits',
    emoji: '🍎',
    group: 'Food & Drink',
    keywords: ['fruit', 'produce', 'sweet'],
    roots: ['07721676-n'],
    maxDepth: 6,
    manualDeny: [
      deny('CLING', 'not fruit in common classroom use'),
      deny('WINDFALL', 'not fruit in common classroom use'),
      deny('MONKEYBREAD', 'confusing food/tree term'),
    ],
  },
  {
    id: 'berries',
    name: 'Berries',
    emoji: '🫐',
    group: 'Food & Drink',
    keywords: ['berry', 'fruit', 'jam'],
    roots: ['07758680-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    emoji: '🥕',
    group: 'Food & Drink',
    keywords: ['vegetable', 'produce', 'garden'],
    roots: ['07723196-n'],
    maxDepth: 6,
    manualDeny: [
      deny('FRIES', 'prepared food, not vegetable'),
      deny('CHILLY', 'misspelling/confusing adjective'),
      deny('JULIENNE', 'cut style, not vegetable'),
    ],
  },
  {
    id: 'nuts',
    name: 'Nuts',
    emoji: '🥜',
    group: 'Food & Drink',
    keywords: ['nut', 'seed', 'snack'],
    roots: ['07753057-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'grains-cereals',
    name: 'Grains & cereals',
    emoji: '🌾',
    group: 'Food & Drink',
    keywords: ['grain', 'cereal', 'wheat', 'rice'],
    roots: ['07818393-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'breads',
    name: 'Breads',
    emoji: '🍞',
    group: 'Food & Drink',
    keywords: ['bread', 'baking', 'loaf'],
    roots: ['07695101-n'],
    maxDepth: 5,
    minWords: 10,
    manualDeny: [
      deny('MEATLOAF', 'not bread'),
      deny('ASHCAKE', 'archaic/obscure bread'),
      deny('CORNDAB', 'obscure classroom fit'),
      deny('HARDTACK', 'archaic/obscure bread'),
      deny('JOURNEYCAKE', 'archaic/obscure bread'),
    ],
  },
  {
    id: 'cheeses',
    name: 'Cheeses',
    emoji: '🧀',
    group: 'Food & Drink',
    keywords: ['cheese', 'dairy', 'food'],
    roots: ['07866305-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'desserts-sweets',
    name: 'Desserts & sweets',
    emoji: '🍰',
    group: 'Food & Drink',
    keywords: ['dessert', 'sweet', 'treat'],
    roots: ['07625449-n', '07612255-n'],
    maxDepth: 5,
    minWords: 10,
    denyTokens: ['BLANCMANGE', 'CANDY', 'DUFF', 'FROZENPUDDING', 'JUNKET', 'MOLD', 'SWEETMEAT'],
    manualDeny: [
      deny('COUGHDROP', 'medicine, not dessert'),
      deny('CANDYKISS', 'previously flagged odd candy term'),
      deny('CHOCOLATEKISS', 'previously flagged odd candy term'),
      deny('MERINGUEKISS', 'previously flagged odd candy term'),
      deny('MOLASSESKISS', 'previously flagged odd candy term'),
      deny('HONEYCRISP', 'apple variety, not dessert'),
      deny('PRUNEWHIP', 'dated/obscure dessert'),
      deny('GUM', 'too generic'),
    ],
  },
  {
    id: 'candy',
    name: 'Candy',
    emoji: '🍬',
    group: 'Food & Drink',
    keywords: ['candy', 'confection', 'sweet'],
    roots: ['07612936-n'],
    maxDepth: 5,
    minWords: 8,
    manualDeny: [
      deny('COUGHDROP', 'medicine, not candy worksheet word'),
      deny('CANDYKISS', 'odd/previously flagged term'),
      deny('CHOCOLATEKISS', 'odd/previously flagged term'),
      deny('MERINGUEKISS', 'odd/previously flagged term'),
      deny('MOLASSESKISS', 'odd/previously flagged term'),
      deny('HONEYCRISP', 'apple variety, not candy'),
    ],
  },
  {
    id: 'beverages',
    name: 'Beverages',
    emoji: '🥤',
    group: 'Food & Drink',
    keywords: ['drink', 'beverage', 'juice'],
    roots: ['07897775-n'],
    excludeRoots: ['07900542-n'],
    maxDepth: 6,
    minWords: 10,
    denyTokens: ['CAFEROYALE', 'COFFEEROYAL', 'LOVEPOTION', 'NEARBEER', 'PHILTER', 'POTION'],
    manualDeny: [
      deny('CIDER', 'can be alcoholic'),
      deny('BIRCHBEER', 'beer wording'),
      deny('ROOTBEER', 'beer wording'),
      deny('DEMITASSE', 'obscure classroom fit'),
      deny('HERBAL', 'adjective, not beverage'),
      deny('RAWMILK', 'food-safety concern'),
      deny('SOURMILK', 'unappealing/food-spoilage term'),
      deny('SCALDEDMILK', 'not beverage in common use'),
      deny('BOILINGWATER', 'not a beverage name'),
      deny('CONDENSEDMILK', 'ingredient, not beverage'),
      deny('EVAPORATEDMILK', 'ingredient, not beverage'),
      deny('POWDEREDMILK', 'ingredient, not beverage'),
    ],
  },
  {
    id: 'pasta',
    name: 'Pasta',
    emoji: '🍝',
    group: 'Food & Drink',
    keywords: ['pasta', 'noodle', 'food'],
    roots: ['07714660-n', '07879350-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'musical-instruments',
    name: 'Musical instruments',
    emoji: '🎺',
    group: 'Things & Tools',
    keywords: ['music', 'instrument', 'sound'],
    roots: ['03806455-n'],
    maxDepth: 7,
    manualDeny: [
      deny('BONES', 'body-part word as instrument'),
      deny('MOUTHBOW', 'obscure classroom fit'),
      deny('HIGHHAT', 'variant spelling/obscure'),
      deny('DRONEPIPE', 'obscure instrument part'),
      deny('LICORICESTICK', 'slang instrument nickname'),
      deny('VIRGINAL', 'potentially awkward term'),
    ],
  },
  {
    id: 'tools',
    name: 'Tools',
    emoji: '🛠️',
    group: 'Things & Tools',
    keywords: ['tool', 'workshop', 'implement'],
    roots: ['04459089-n'],
    excludeRoots: ['04572661-n'],
    maxDepth: 7,
    denyTokens: [
      'BENDER',
      'BILL',
      'CLEAVER',
      'CORKSCREW',
      'DROVE',
      'GANG',
      'GRAVER',
      'GUTTER',
      'HECKLE',
      'RAZOR',
      'SMOOTHER',
      'STYLE',
      'UPSET',
    ],
    manualDeny: [
      deny('BATTERINGRAM', 'violent tool'),
      deny('ROACHCLIP', 'drug paraphernalia'),
      deny('SWITCHBLADE', 'weapon'),
      deny('ICEPICK', 'weapon association'),
      deny('HANDAX', 'weapon association'),
      deny('ICEAX', 'weapon association'),
      deny('SNUFFERS', 'archaic/obscure classroom fit'),
      deny('CHURCHKEY', 'beer-can opener association'),
      deny('BOTTLEOPENER', 'alcohol association'),
      deny('BOTTLESCREW', 'alcohol association'),
    ],
  },
  {
    id: 'kitchen-utensils',
    name: 'Kitchen utensils',
    emoji: '🍴',
    group: 'Things & Tools',
    keywords: ['kitchen', 'utensil', 'cooking'],
    roots: ['04523967-n', '03158041-n'],
    maxDepth: 6,
    minWords: 10,
    manualDeny: [
      deny('SAUSAGEMAKER', 'processed meat tool, poor classroom fit'),
      deny('CAULDRON', 'witch/occult connotation'),
      deny('CHAFINGDISH', 'obscure classroom fit'),
      deny('SAMOVAR', 'obscure classroom fit'),
      deny('SUGARSHELL', 'obscure utensil'),
    ],
  },
  {
    id: 'containers',
    name: 'Containers',
    emoji: '📦',
    group: 'Things & Tools',
    keywords: ['container', 'box', 'holder'],
    roots: ['03099154-n'],
    maxDepth: 4,
    manualDeny: [
      deny('ASHCAN', 'trash term'),
      deny('ASHTRAY', 'tobacco related'),
      deny('COFFIN', 'death-related'),
      deny('RUMMER', 'alcohol vessel'),
      deny('SCHOONER', 'alcohol vessel/common ambiguity'),
      deny('TANKARD', 'alcohol vessel'),
      deny('BEDPAN', 'bathroom/medical container'),
      deny('JIGGER', 'alcohol measure'),
      deny('SNIFTER', 'alcohol vessel'),
      deny('THUNDERMUG', 'toilet slang'),
      deny('BEERCAN', 'alcohol related'),
      deny('BEERGLASS', 'alcohol related'),
      deny('BODYBAG', 'death-related'),
      deny('BURNBAG', 'destruction/death connotation'),
      deny('CENSER', 'religious ritual object'),
      deny('COLLECTIONPLATE', 'religious/church object'),
      deny('GRACECUP', 'religious/alcohol connotation'),
      deny('LIQUEURGLASS', 'alcohol related'),
      deny('SNUFFBOX', 'tobacco related'),
      deny('SPITTOON', 'tobacco/spitting related'),
      deny('TOILETBAG', 'bathroom term'),
      deny('BIER', 'funeral/death related'),
      deny('SARCOPHAGUS', 'death-related'),
      deny('AMMUNITIONCHEST', 'weapon related'),
      deny('BAPTISTERY', 'religious object'),
      deny('BEERBARREL', 'alcohol related'),
      deny('BEERBOTTLE', 'alcohol related'),
      deny('FINGERBOWL', 'obscure classroom fit'),
      deny('GASHOLDER', 'utility/unsafe association'),
      deny('GASTANK', 'fuel/unsafe association'),
      deny('MUMMYBAG', 'death-related'),
      deny('PILLBOTTLE', 'drug/medicine related'),
      deny('PUNCHBOWL', 'alcohol-party association'),
      deny('SLOPPAIL', 'waste container'),
      deny('SMELLINGBOTTLE', 'dated medical term'),
      deny('CESSPOOL', 'sewage-related'),
      deny('SHOTGLASS', 'alcohol related'),
      deny('BEERKEG', 'alcohol related'),
      deny('STEIN', 'beer vessel'),
      deny('FUELPOD', 'fuel/unsafe association'),
      deny('GASOLINETANK', 'fuel/unsafe association'),
      deny('POWDERHORN', 'weapon related'),
      deny('DICECUP', 'gambling/game chance object'),
      deny('INHALER', 'medical/drug device'),
      deny('SICKBAG', 'vomit/illness container'),
      deny('SWEATBAG', 'unpleasant/odd term'),
      deny('CASKET', 'death-related'),
      deny('URN', 'funeral association'),
      deny('PYX', 'religious vessel'),
      deny('CHALICE', 'religious/alcohol vessel'),
      deny('MANGER', 'religious nativity association'),
      deny('FLUTEGLASS', 'alcohol vessel'),
      deny('CHAMPAGNEFLUTE', 'alcohol vessel'),
      deny('BEERMUG', 'alcohol vessel'),
      deny('TUN', 'alcohol vat'),
      deny('DEMIJOHN', 'alcohol/chemical vessel'),
      deny('CARBOY', 'alcohol/chemical vessel'),
      deny('CAULDRON', 'occult/witch connotation'),
      deny('PETROLTANK', 'fuel/unsafe association'),
      deny('SUMP', 'waste pit'),
      deny('SPECIMENBOTTLE', 'medical specimen container'),
      deny('PIGBED', 'odd/unpleasant container term'),
      deny('SILENTBUTLER', 'servile/obscure term'),
    ],
  },
  {
    id: 'furniture',
    name: 'Furniture',
    emoji: '🪑',
    group: 'Things & Tools',
    keywords: ['furniture', 'chair', 'table'],
    roots: ['03410635-n'],
    maxDepth: 4,
    manualDeny: [
      deny('ALTAR', 'religious object'),
      deny('PEW', 'religious object'),
      deny('THRONE', 'power/royalty, not classroom furniture common'),
      deny('OPERATINGTABLE', 'medical/surgery related'),
      deny('TOILETSEAT', 'bathroom term'),
      deny('FIGHTINGCHAIR', 'violent wording'),
      deny('PENALTYBOX', 'punishment term'),
      deny('SICKBED', 'illness/death connotation'),
      deny('CASHBAR', 'alcohol related'),
      deny('OYSTERBAR', 'bar/alcohol association'),
      deny('SALADBAR', 'restaurant fixture, not furniture'),
      deny('SNACKBAR', 'restaurant fixture, not furniture'),
      deny('WETBAR', 'alcohol related'),
      deny('MERCYSEAT', 'religious object'),
      deny('MILKBAR', 'bar wording'),
      deny('LOWER', 'not furniture'),
      deny('PLATEN', 'not furniture in common classroom use'),
      deny('COMMUNIONTABLE', 'religious furniture'),
      deny('CHOIRSTALL', 'religious furniture'),
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    emoji: '🚗',
    group: 'Things & Tools',
    keywords: ['vehicle', 'transport', 'car'],
    roots: ['04531608-n'],
    excludeRoots: ['04559982-n', '02871055-n', '04396120-n', '02742894-n', '03925218-n', '02743305-n', '04573847-n'],
    maxDepth: 6,
    denyTokens: ['ELECTRIC', 'LORRY'],
    manualDeny: [
      deny('HEARSE', 'death-related vehicle'),
      deny('SHIPWRECK', 'disaster/death related'),
      deny('TINCAN', 'warship slang'),
      deny('DINKY', 'dated/insulting adjective'),
      deny('TROOPCARRIER', 'military vehicle'),
      deny('TROOPTRANSPORT', 'military vehicle'),
      deny('TROOPSHIP', 'military vehicle'),
      deny('WARSHIP', 'military vehicle'),
      deny('DREADNOUGHT', 'warship'),
      deny('GUNBOAT', 'military vehicle'),
      deny('BATTLECRUISER', 'warship'),
      deny('MINESWEEPER', 'warship'),
      deny('STEALTHFIGHTER', 'military aircraft'),
      deny('INTERCEPTOR', 'military aircraft'),
      deny('HANGARQUEEN', 'slang/obscure aircraft term'),
      deny('TUMBREL', 'execution/death association'),
      deny('POLICECRUISER', 'law-enforcement vehicle'),
      deny('LANDINGCRAFT', 'military landing vehicle'),
      deny('SHOOTINGBRAKE', 'weapon word in vehicle name'),
      deny('ARK', 'religious story association'),
    ],
  },
  {
    id: 'boats-ships',
    name: 'Boats & ships',
    emoji: '⛵',
    group: 'Things & Tools',
    keywords: ['boat', 'ship', 'watercraft'],
    roots: ['02861626-n', '04201332-n'],
    excludeRoots: ['04559982-n', '04354832-n'],
    maxDepth: 6,
    manualDeny: [
      deny('SHIPWRECK', 'disaster/death related'),
      deny('WARSHIP', 'military ship'),
      deny('GUNBOAT', 'military ship'),
      deny('MINESWEEPER', 'military ship'),
      deny('TROOPSHIP', 'military ship'),
      deny('DREADNOUGHT', 'warship'),
      deny('TINCAN', 'warship slang'),
      deny('BATTLECRUISER', 'warship'),
      deny('NAUTILUS', 'submarine/warship association'),
      deny('ARK', 'religious story association'),
    ],
  },
  {
    id: 'aircraft',
    name: 'Aircraft',
    emoji: '✈️',
    group: 'Things & Tools',
    keywords: ['aircraft', 'plane', 'flying'],
    roots: ['02689427-n'],
    excludeRoots: ['02871055-n'],
    maxDepth: 6,
    manualDeny: [
      deny('STEALTHFIGHTER', 'military aircraft'),
      deny('INTERCEPTOR', 'military aircraft'),
      deny('HANGARQUEEN', 'slang/obscure aircraft term'),
      deny('DELTAWING', 'technical/obscure aircraft term'),
    ],
  },
  {
    id: 'buildings',
    name: 'Buildings',
    emoji: '🏫',
    group: 'Things & Tools',
    keywords: ['building', 'structure', 'place'],
    roots: ['02916498-n'],
    maxDepth: 4,
    manualDeny: [
      deny('CHAPEL', 'religious building'),
      deny('TEMPLE', 'religious building'),
      deny('PUB', 'alcohol related'),
      deny('MORGUE', 'death-related'),
      deny('CATHEDRAL', 'religious building'),
      deny('BUTCHERY', 'violent/meat-processing connotation'),
      deny('COURTHOUSE', 'legal/punishment connotation'),
      deny('OUTHOUSE', 'toilet-related'),
      deny('SHRINE', 'religious building'),
      deny('MOSQUE', 'religious building'),
      deny('SYNAGOGUE', 'religious building'),
      deny('ABBEY', 'religious building'),
      deny('CLOISTER', 'religious building'),
      deny('PARSONAGE', 'religious building'),
      deny('CONVENT', 'religious building'),
      deny('MADHOUSE', 'dated/offensive mental-health term'),
      deny('MONASTERY', 'religious building'),
      deny('GAMBLINGHOUSE', 'gambling related'),
      deny('FIRETRAP', 'danger/death connotation'),
      deny('FUNERALHOME', 'death-related'),
      deny('HASHHOUSE', 'dated/odd term'),
      deny('HUNTINGLODGE', 'hunting/weapon association'),
      deny('MANSE', 'religious building'),
      deny('RATHSKELLER', 'bar/alcohol association'),
      deny('BURNCENTER', 'injury-related'),
      deny('CREMATORY', 'death-related'),
      deny('FRATERNITYHOUSE', 'college/adult association'),
      deny('MASSAGEPARLOR', 'adult/sexual connotation'),
      deny('SAFEHOUSE', 'crime/violence connotation'),
      deny('SHOOTINGLODGE', 'weapon association'),
      deny('BASILICA', 'religious building'),
      deny('FREEHOUSE', 'pub/alcohol related'),
      deny('MINSTER', 'religious building'),
      deny('PRIORY', 'religious building'),
      deny('NUNNERY', 'religious building'),
      deny('LAMASERY', 'religious building'),
      deny('MORTUARY', 'death-related'),
      deny('ABATTOIR', 'slaughter/death related'),
      deny('GAMBLINGDEN', 'gambling related'),
      deny('FUNERALPARLOR', 'death-related'),
      deny('CREMATORIUM', 'death-related'),
      deny('PUBLICHOUSE', 'pub/alcohol related'),
      deny('SHOOTINGBOX', 'weapon association'),
      deny('VICARAGE', 'religious building'),
      deny('CRAZYHOUSE', 'dated/offensive mental-health term'),
      deny('PAGODA', 'religious building'),
      deny('SANATORIUM', 'illness/disease connotation'),
      deny('DISPENSARY', 'medicine/drug association'),
      deny('FLOPHOUSE', 'derogatory housing term'),
      deny('GAMBLINGHELL', 'gambling related'),
      deny('SLAUGHTERHOUSE', 'death/slaughter related'),
      deny('DEADROOM', 'death-related'),
      deny('FUNERALCHURCH', 'death/religious building'),
      deny('GINMILL', 'alcohol related'),
      deny('SANITARIUM', 'illness/disease connotation'),
      deny('RECTORY', 'religious building'),
      deny('FUNNYFARM', 'dated/offensive mental-health term'),
      deny('GAMINGHOUSE', 'gambling related'),
      deny('FUNNYHOUSE', 'dated/offensive mental-health term'),
    ],
  },
  {
    id: 'clothing',
    name: 'Clothing',
    emoji: '👕',
    group: 'Things & Tools',
    keywords: ['clothing', 'clothes', 'wear'],
    roots: ['03055525-n'],
    maxDepth: 4,
    manualDeny: [
      deny('BRASSIERE', 'intimate clothing'),
      deny('DIAPER', 'toileting-related'),
      deny('LOINCLOTH', 'intimate/minimal clothing'),
      deny('UNDERGARMENT', 'intimate clothing'),
      deny('BIKINI', 'revealing clothing'),
      deny('KNICKERS', 'underwear term'),
      deny('VESTMENT', 'religious clothing'),
      deny('UNDERPANTS', 'intimate clothing'),
      deny('UNDERWEAR', 'intimate clothing'),
      deny('BRIEFS', 'intimate clothing'),
      deny('DRAWERS', 'intimate clothing'),
      deny('LINGERIE', 'sexualized clothing'),
      deny('PANTIE', 'intimate clothing'),
      deny('THIGHPAD', 'awkward body-area term'),
      deny('THROATPROTECTOR', 'body danger term'),
      deny('DUNCECAP', 'shaming/insulting term'),
      deny('MINISKIRT', 'adult/revealing connotation'),
      deny('GARTERBELT', 'sexualized clothing'),
      deny('HOBBLESKIRT', 'dated/restrictive term'),
      deny('MONASTICHABIT', 'religious clothing'),
      deny('SKULLCAP', 'religious/loaded term'),
      deny('STRAPLESS', 'revealing clothing'),
      deny('SWIMMINGTRUNKS', 'intimate swimwear'),
      deny('BANDOLEER', 'ammunition/weapon related'),
      deny('CASSOCK', 'religious clothing'),
      deny('CHASUBLE', 'religious clothing'),
      deny('FALSEFACE', 'mask/fright connotation'),
      deny('SKIVVIES', 'underwear slang'),
      deny('SURPLICE', 'religious clothing'),
      deny('YARMULKE', 'religious clothing'),
      deny('PONTIFICAL', 'religious clothing'),
      deny('SUPPORTHOSE', 'medical/intimate clothing'),
      deny('TRUNKHOSE', 'archaic/intimate-sounding clothing'),
      deny('UNDIES', 'underwear slang'),
      deny('BRA', 'intimate clothing'),
      deny('NAPPY', 'toileting-related'),
      deny('BOXERS', 'intimate clothing'),
      deny('SCANTY', 'revealing/sexualized term'),
      deny('UNMENTIONABLE', 'underwear euphemism'),
      deny('BATHINGTRUNKS', 'intimate swimwear'),
      deny('CAMISOLE', 'intimate clothing'),
      deny('CHEMISE', 'intimate clothing'),
      deny('MINI', 'revealing clothing shorthand'),
      deny('UNIONSUIT', 'underwear'),
      deny('INTIMATEAPPAREL', 'intimate clothing'),
      deny('UNDERCLOTHES', 'intimate clothing'),
      deny('STAYS', 'undergarment'),
      deny('MUFF', 'sexual/crude slang ambiguity'),
      deny('WEEDS', 'mourning clothes/death connotation'),
      deny('BIRETTA', 'religious clothing'),
      deny('ALB', 'religious clothing'),
      deny('CARTRIDGEBELT', 'ammunition/weapon related'),
      deny('GARRISONCAP', 'military clothing'),
      deny('SKIDLID', 'slang/obscure helmet term'),
      deny('CORSET', 'intimate/restrictive garment'),
      deny('UNDERCLOTHING', 'intimate clothing'),
      deny('UNDERSHIRT', 'undergarment'),
      deny('OVERSEASCAP', 'military clothing'),
      deny('SAILORCAP', 'military/uniform clothing'),
      deny('SAILORSUIT', 'military/uniform clothing'),
      deny('SAFETYBELT', 'not clothing'),
      deny('SEATBELT', 'not clothing'),
      deny('SACKCLOTH', 'mourning/religious connotation'),
      deny('DRESSINGSACK', 'archaic garment'),
      deny('WIMPLE', 'religious/archaic clothing'),
      deny('STOLE', 'religious clothing ambiguity'),
      deny('TROUSSEAU', 'bridal/adult term'),
      deny('BATHINGCAP', 'swimwear/body-related'),
      deny('BATHROBE', 'bath/private clothing'),
      deny('SWIMSUIT', 'revealing swimwear'),
      deny('TANKSUIT', 'revealing swimwear'),
    ],
  },
  {
    id: 'footwear',
    name: 'Footwear',
    emoji: '👟',
    group: 'Things & Tools',
    keywords: ['footwear', 'shoe', 'boot'],
    roots: ['03385972-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'hats',
    name: 'Hats',
    emoji: '🎩',
    group: 'Things & Tools',
    keywords: ['hat', 'cap', 'headwear'],
    roots: ['03502782-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'fabrics',
    name: 'Fabrics',
    emoji: '🧵',
    group: 'Things & Tools',
    keywords: ['fabric', 'cloth', 'textile'],
    roots: ['03314753-n'],
    maxDepth: 6,
    minWords: 10,
    manualDeny: [
      deny('RAG', 'low-quality/derogatory common meaning'),
      deny('COBWEB', 'not fabric in common use'),
      deny('PASTY', 'not fabric in common use'),
      deny('LUG', 'not fabric in common use'),
      deny('SHARKSKIN', 'animal skin term'),
      deny('CHICKENWIRE', 'not fabric'),
      deny('FORESAIL', 'sail, not classroom fabric'),
      deny('MAINSAIL', 'sail, not classroom fabric'),
      deny('TOPSAIL', 'sail, not classroom fabric'),
      deny('JIB', 'sail, not classroom fabric'),
      deny('SPINNAKER', 'sail, not classroom fabric'),
    ],
  },
  {
    id: 'toys',
    name: 'Toys',
    emoji: '🧸',
    group: 'Things & Tools',
    keywords: ['toy', 'plaything', 'game'],
    roots: ['03971038-n'],
    maxDepth: 6,
    minWords: 8,
    manualDeny: [
      deny('SLINGSHOT', 'weapon-like toy'),
      deny('WATERGUN', 'weapon-like toy'),
      deny('CORKGUN', 'weapon-like toy'),
      deny('ERECTIONRING', 'sexual anatomy phrase'),
      deny('TOYSOLDIER', 'military toy'),
      deny('WHIPPINGTOP', 'violent wording'),
      deny('GOATEYE', 'obscure/bizarre toy'),
      deny('SQUIRTGUN', 'weapon-like toy'),
      deny('TENSIONRING', 'sexual anatomy phrase'),
      deny('WHIPTOP', 'violent wording'),
    ],
  },
  {
    id: 'games',
    name: 'Games',
    emoji: '🎲',
    group: 'Things & Tools',
    keywords: ['game', 'contest', 'play'],
    roots: ['00456623-n'],
    excludeRoots: ['00524569-n'],
    maxDepth: 6,
    minWords: 10,
    denyTokens: [
      'BLACKJACK',
      'BOODLE',
      'CRAPS',
      'DRAWING',
      'FANTAN',
      'LOTTERY',
      'PILLOWFIGHT',
      'POSTOFFICE',
      'RAFFLE',
      'ROULETTE',
      'SWEEPSTAKES',
    ],
    manualDeny: [
      deny('GINRUMMY', 'alcohol word in game name'),
      deny('LUCKYDIP', 'gambling/chance connotation'),
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    group: 'People & Activities',
    keywords: ['sport', 'athletics', 'competition'],
    roots: ['00524569-n'],
    maxDepth: 6,
    denyTokens: ['COURSING', 'FIGHT', 'HUNT', 'HUNTING'],
    manualDeny: [
      deny('DUCKING', 'dated/unclear sport'),
      deny('TROLLING', 'negative common meaning'),
      deny('FLYINGMARE', 'obscure/violent wrestling move'),
    ],
  },
  {
    id: 'dances',
    name: 'Dances',
    emoji: '💃',
    group: 'People & Activities',
    keywords: ['dance', 'movement', 'music'],
    roots: ['00429255-n'],
    maxDepth: 6,
    minWords: 8,
    manualDeny: [
      deny('STRIPSHOW', 'sexual/adult entertainment'),
    ],
  },
  {
    id: 'occupations',
    name: 'Occupations',
    emoji: '👩‍🏫',
    group: 'People & Activities',
    keywords: ['job', 'worker', 'career'],
    roots: ['09655706-n', '10499838-n', '10073616-n'],
    maxDepth: 3,
    denyTokens: [
      'ACCOMPLICE',
      'AIRMAN',
      'ARMORER',
      'BEATER',
      'BLUEJACKET',
      'BOTTOMDOG',
      'CHAR',
      'DOMESTIC',
      'FAMILIAR',
      'FULLER',
      'FLUNKY',
      'GENTLEMAN',
      'GUTTER',
      'HANGER',
      'HANGOVER',
      'HATCHETWOMAN',
      'HELP',
      'HIRE',
      'INDEPENDENT',
      'INSTRUMENT',
      'LOVELY',
      'LOADER',
      'MAN',
      'MANNEQUIN',
      'MARINE',
      'MENIAL',
      'MISSIONARY',
      'ORDINARY',
      'PRIVATE',
      'PUNTER',
      'RECRUIT',
      'SCAB',
      'SALESMAN',
      'SMITH',
      'SERVANT',
      'SLAVE',
      'SOLDIER',
      'SUBSIDIARY',
      'SUPPORTER',
      'TEMPORARY',
      'UNDERTAKER',
      'VET',
      'VIGILANTE',
      'VOLUNTARY',
    ],
    manualDeny: [
      deny('COG', 'servile/dehumanizing connotation'),
      deny('COURSER', 'not occupation in common use'),
      deny('HUNTER', 'weapon/animal killing occupation'),
      deny('TRAPPER', 'animal trapping occupation'),
      deny('WHALER', 'animal killing occupation'),
      deny('SLAUGHTERER', 'violent/meat-killing occupation'),
      deny('ENFORCER', 'violence/crime connotation'),
      deny('PARATROOPER', 'military occupation'),
      deny('MACHINEGUNNER', 'weapon/military occupation'),
      deny('LEATHERNECK', 'military slang'),
      deny('KNACKER', 'animal slaughter/death occupation'),
      deny('SKIVVY', 'servile/dated term'),
      deny('PEON', 'servile/derogatory term'),
      deny('DELIVERYBOY', 'dated gendered job title'),
      deny('OFFICEBOY', 'dated gendered job title'),
      deny('CABINBOY', 'dated gendered job title'),
      deny('CABINGIRL', 'dated gendered job title'),
      deny('GROCERYBOY', 'dated gendered job title'),
      deny('NEWSBOY', 'dated gendered job title'),
      deny('PAPERBOY', 'dated gendered job title'),
      deny('SERVINGGIRL', 'dated/servile gendered job title'),
      deny('CAREERGIRL', 'dated gendered phrase'),
      deny('CAREERMAN', 'dated gendered phrase'),
      deny('COMPANYMAN', 'servile/diminishing connotation'),
      deny('COMPANYWOMAN', 'servile/diminishing connotation'),
      deny('ORGANIZATIONMAN', 'servile/diminishing connotation'),
      deny('RAILROADMAN', 'dated gendered job title'),
      deny('RAILROADWOMAN', 'dated gendered job title'),
      deny('WORKINGWOMAN', 'dated/adult connotation'),
      deny('GYNECOLOGIST', 'sensitive anatomy specialty'),
      deny('OBSTETRICIAN', 'sensitive reproductive specialty'),
      deny('EMBALMER', 'death-related occupation'),
      deny('TAXIDERMIST', 'death/animal remains occupation'),
      deny('FUMIGATOR', 'poison/chemical occupation'),
      deny('PUBLICAN', 'alcohol/pub occupation'),
      deny('BUNNY', 'adult/sexualized job sense'),
      deny('DEACON', 'religious office'),
      deny('CHURCHOFFICER', 'religious office'),
      deny('PLEDGETAKER', 'obscure/odd occupation'),
      deny('YUPPIE', 'dated/derogatory social label'),
      deny('SUBORDINATE', 'servile/dehumanizing job term'),
      deny('LACKEY', 'servile/derogatory term'),
      deny('VALET', 'servile dated role'),
      deny('BUTLER', 'servile dated role'),
      deny('MAID', 'servile dated role'),
      deny('GOVERNESS', 'dated gendered role'),
      deny('FOOTMAN', 'servile dated role'),
      deny('SCULLION', 'servile/archaic role'),
      deny('FACTOTUM', 'servile/obscure role'),
      deny('GOFER', 'servile/derogatory role'),
      deny('SEAMAN', 'awkward classroom ambiguity'),
      deny('SQUIRE', 'archaic status term'),
      deny('SWAGGER', 'not occupation in common use'),
      deny('FODDER', 'not occupation'),
      deny('EMPLOYABLE', 'adjective, not occupation'),
      deny('MOONLIGHTER', 'adult/side-work connotation'),
      deny('BLASTER', 'explosive occupation'),
      deny('BREAKER', 'not clear occupation'),
      deny('WATERBOY', 'dated servile/gendered role'),
      deny('WATERGIRL', 'dated servile/gendered role'),
      deny('WATERDOG', 'not occupation'),
      deny('SHOPBOY', 'dated gendered job title'),
      deny('SHOPGIRL', 'dated gendered job title'),
      deny('CLEANINGMAN', 'dated gendered job title'),
      deny('AIRHOST', 'dated gendered job title'),
      deny('GARNISHEE', 'legal target, not occupation'),
      deny('SECONDFIDDLE', 'idiom, not occupation'),
      deny('VIGILANCEMAN', 'vigilante connotation'),
      deny('VIGILANCEWOMAN', 'vigilante connotation'),
      deny('MEDICALMAN', 'dated gendered job title'),
      deny('MEDICALWOMAN', 'dated gendered job title'),
      deny('TAVERNKEEPER', 'alcohol/pub occupation'),
      deny('BARMAID', 'alcohol/gendered occupation'),
      deny('DEVILDOG', 'military slang'),
      deny('ENLISTEDPERSON', 'military occupation'),
      deny('HUNTRESS', 'hunting/weapon occupation'),
      deny('HUNTSMAN', 'hunting/weapon occupation'),
      deny('UNDERLING', 'servile/derogatory term'),
      deny('MORTICIAN', 'death-related occupation'),
      deny('ABORTIONIST', 'sensitive/adult medical occupation'),
      deny('CLEANINGWOMAN', 'dated gendered job title'),
      deny('CAREERWOMAN', 'dated gendered phrase'),
      deny('RAILWAYMAN', 'dated gendered job title'),
      deny('RAILWAYWOMAN', 'dated gendered job title'),
      deny('SERVICEMAN', 'military/gendered job title'),
      deny('SERVICEWOMAN', 'military/gendered job title'),
      deny('NAVALOFFICER', 'military occupation'),
      deny('NAVYMAN', 'military/gendered job title'),
      deny('NAVYWOMAN', 'military/gendered job title'),
      deny('COLORGUARD', 'military/parade role'),
      deny('KITCHENPOLICE', 'military punishment role'),
      deny('LAMEDUCK', 'derogatory idiom'),
      deny('NUNCIO', 'religious diplomatic office'),
      deny('SEXTON', 'church/death-related job'),
      deny('BESTMAN', 'wedding role, not occupation'),
      deny('CHECKGIRL', 'dated gendered job title'),
      deny('COVERBOY', 'dated/modeling title'),
      deny('COVERGIRL', 'dated/sexualized modeling title'),
      deny('SUPERMODEL', 'adult/fashion modeling term'),
      deny('COURTIER', 'archaic court role'),
      deny('VIZIER', 'archaic court role'),
      deny('PLENIPOTENTIARY', 'obscure diplomatic title'),
      deny('GOB', 'naval slang'),
      deny('ROCKER', 'not occupation in common use'),
      deny('BELLBOY', 'dated gendered service role'),
      deny('BUSBOY', 'dated gendered service role'),
      deny('STEWARDESS', 'dated gendered job title'),
      deny('WAITRESS', 'gendered job title'),
      deny('FUNERALDIRECTOR', 'death-related occupation'),
      deny('WATERRAT', 'not occupation / insulting animal phrase'),
      deny('CLEANINGLADY', 'dated gendered job title'),
      deny('WORKMAN', 'dated gendered job title'),
      deny('SALESWOMAN', 'gendered job title'),
      deny('FISHERMAN', 'gendered job title'),
      deny('MILKMAN', 'gendered job title'),
      deny('POSTMAN', 'gendered job title'),
      deny('WASHERWOMAN', 'dated gendered job title'),
      deny('CITYFATHER', 'dated gendered civic title'),
      deny('HEADMISTRESS', 'gendered job title'),
      deny('PROPERTYMAN', 'gendered job title'),
      deny('PROPERTYWOMAN', 'gendered job title'),
      deny('BATBOY', 'gendered sports role'),
      deny('BOATMAN', 'gendered job title'),
      deny('COACHMAN', 'dated gendered job title'),
      deny('CREWMAN', 'gendered job title'),
      deny('HARDHAT', 'slang for worker'),
    ],
  },
  {
    id: 'bones',
    name: 'Bones',
    emoji: '🦴',
    group: 'Science & Nature',
    keywords: ['bone', 'skeleton', 'anatomy'],
    roots: ['05277400-n'],
    maxDepth: 6,
    minWords: 8,
    manualDeny: [
      deny('ANTERIOR', 'adjective, not bone'),
      deny('PEARLY', 'not bone'),
    ],
  },
  {
    id: 'gemstones',
    name: 'Gemstones',
    emoji: '💎',
    group: 'Science & Nature',
    keywords: ['gem', 'gemstone', 'jewel'],
    roots: ['14723913-n'],
    maxDepth: 5,
    minWords: 8,
    manualDeny: [
      deny('CARBUNCLE', 'also skin infection'),
      deny('ADAMANT', 'archaic/obscure gemstone'),
    ],
  },
  {
    id: 'minerals',
    name: 'Minerals',
    emoji: '🔬',
    group: 'Science & Nature',
    keywords: ['mineral', 'crystal', 'geology'],
    roots: ['14686753-n'],
    maxDepth: 5,
    manualDeny: [
      deny('ASBESTOS', 'hazardous material'),
      deny('CINNABAR', 'toxic mercury mineral'),
      deny('PITCHBLENDE', 'radioactive mineral'),
      deny('MINERALTAR', 'tar/asphalt term'),
      deny('MINERALPITCH', 'tar/asphalt term'),
      deny('PAYDIRT', 'not mineral in common use'),
      deny('CARBUNCLE', 'also skin infection'),
    ],
  },
  {
    id: 'rocks',
    name: 'Rocks',
    emoji: '🪨',
    group: 'Science & Nature',
    keywords: ['rock', 'stone', 'geology'],
    roots: ['14720954-n', '09438954-n'],
    maxDepth: 5,
    minWords: 10,
    manualDeny: [
      deny('CALCULUS', 'body/math term, not rock for kids'),
      deny('GALLSTONE', 'medical/body stone'),
      deny('BELAY', 'not rock in common use'),
      deny('GUIDEPLATE', 'not rock'),
      deny('TUBULARDEVICE', 'not rock'),
      deny('ROADMETAL', 'obscure construction term'),
      deny('SHINGLING', 'not rock in common use'),
    ],
  },
  {
    id: 'metals-elements',
    name: 'Metals & elements',
    emoji: '⚗️',
    group: 'Science & Nature',
    keywords: ['metal', 'element', 'chemistry'],
    roots: ['14647071-n', '14649636-n'],
    maxDepth: 4,
    minWords: 10,
    manualDeny: [
      deny('MERCURY', 'toxic substance/common hazard'),
      deny('URANIUM', 'radioactive element'),
      deny('PLUTONIUM', 'radioactive element'),
      deny('RADIUM', 'radioactive element'),
      deny('POLONIUM', 'radioactive element'),
      deny('NEPTUNIUM', 'radioactive element'),
      deny('LAWRENCIUM', 'radioactive element'),
      deny('ACTINIUM', 'radioactive element'),
      deny('THORIUM', 'radioactive element'),
      deny('RADON', 'radioactive gas'),
      deny('CHAR', 'burn/death connotation'),
      deny('SOOT', 'dirty combustion residue'),
      deny('CINDERPIG', 'obscure metallurgy term'),
      deny('MINEPIG', 'obscure metallurgy term'),
      deny('PIGLEAD', 'obscure metallurgy term'),
      deny('HARDLEAD', 'obscure metallurgy term'),
      deny('BONEBLACK', 'bone/death related pigment'),
      deny('BLACKDIAMOND', 'not element/metal'),
      deny('BUCKYBALL', 'advanced/obscure chemistry term'),
    ],
  },
  {
    id: 'colors',
    name: 'Colors',
    emoji: '🎨',
    group: 'Science & Nature',
    keywords: ['color', 'colour', 'hue'],
    roots: ['04963771-n'],
    excludeRoots: ['04984219-n'],
    maxDepth: 5,
    minWords: 10,
    manualDeny: [
      deny('SANGUINE', 'blood-related common meaning'),
      deny('HOARINESS', 'awkward/age-related term'),
      deny('BLEACH', 'chemical product, not color for kids'),
      deny('DRAB', 'negative descriptor'),
    ],
  },
  {
    id: 'geometric-shapes',
    name: 'Geometric shapes',
    emoji: '🔷',
    group: 'Science & Nature',
    keywords: ['shape', 'geometry', 'figure'],
    roots: ['13885789-n', '13888765-n', '13896141-n', '13906542-n', '13921893-n', '13895231-n', '13887919-n', '13937623-n'],
    maxDepth: 5,
    minWords: 10,
    denyTokens: ['BOX', 'BUST', 'MOBILE', 'MODELING', 'MOLD', 'RELIEF', 'TERM', 'TREE', 'TREEDIAGRAM'],
    manualDeny: [
      deny('MOTHBALL', 'pesticide/chemical object'),
      deny('LATHER', 'not shape in common use'),
      deny('SPUME', 'obscure foam word'),
      deny('WHITEWATER', 'not geometric shape'),
      deny('GARDENROLLER', 'tool, not shape'),
      deny('PAINTROLLER', 'tool, not shape'),
      deny('SPROCKET', 'machine part, not shape'),
      deny('CRYSTALBALL', 'fortune-telling/occult object'),
      deny('CONGLOMERATION', 'abstract, not geometry shape'),
      deny('IDEALSOLID', 'technical/obscure'),
    ],
  },
  {
    id: 'weather-phenomena',
    name: 'Weather phenomena',
    emoji: '🌦️',
    group: 'Science & Nature',
    keywords: ['weather', 'storm', 'cloud'],
    roots: ['11545095-n'],
    maxDepth: 6,
    minWords: 10,
    manualDeny: [
      deny('QUIET', 'abstract condition, not weather phenomenon'),
      deny('LOW', 'abstract pressure shorthand'),
      deny('CLEMENCY', 'abstract/mercy meaning'),
      deny('INCLEMENCY', 'abstract/rare word'),
      deny('WHIFF', 'not weather phenomenon'),
      deny('SANDBLAST', 'hazard/injury connotation'),
      deny('SNOWEATER', 'obscure regional term'),
      deny('TEMPESTUOUSNESS', 'abstract/rare word'),
      deny('BOISTEROUSNESS', 'abstract/rare word'),
      deny('CHOPPINESS', 'water condition, not weather'),
    ],
  },
  {
    id: 'bodies-of-water',
    name: 'Bodies of water',
    emoji: '🌊',
    group: 'Science & Nature',
    keywords: ['water', 'river', 'lake', 'ocean'],
    roots: ['09248053-n'],
    maxDepth: 6,
    minWords: 10,
    manualDeny: [
      deny('MAIN', 'archaic sea term'),
      deny('WALLOW', 'mud/animal wallow, poor fit'),
      deny('SEVENSEAS', 'idiom rather than body type'),
      deny('HIGHSEAS', 'legal/idiom phrase'),
    ],
  },
  {
    id: 'landforms',
    name: 'Landforms',
    emoji: '⛰️',
    group: 'Science & Nature',
    keywords: ['landform', 'geology', 'mountain'],
    roots: ['09310874-n'],
    maxDepth: 6,
    minWords: 10,
    manualDeny: [
      deny('WORMHOLE', 'science-fiction/physics term, not landform'),
      deny('BONANZA', 'not landform in common use'),
      deny('TWILIGHTZONE', 'pop-culture phrase, not landform'),
      deny('LANDFILL', 'garbage/waste site'),
      deny('DIVOT', 'sports turf mark, not landform'),
      deny('PIT', 'danger/hole term'),
      deny('BURROW', 'animal hole, not landform type'),
      deny('WARREN', 'animal burrow network, not landform'),
    ],
  },
  {
    id: 'school-subjects',
    name: 'School subjects',
    emoji: '📚',
    group: 'Science & Nature',
    keywords: ['school', 'subject', 'discipline'],
    roots: ['06005806-n'],
    maxDepth: 4,
    minWords: 10,
    denyTokens: ['BUSINESS', 'MEMORY', 'METHOD', 'MODELING', 'OBJECT', 'PHRASE', 'PLAYING', 'STRATEGY', 'TACTICS', 'VARIATION'],
    manualDeny: [
      deny('THEOLOGY', 'religious/proselytizing concern'),
      deny('ESCHATOLOGY', 'religious/death-related subject'),
      deny('NUMEROLOGY', 'pseudoscience/occult'),
      deny('GRAPHOLOGY', 'pseudoscience'),
      deny('EUGENICS', 'offensive/harmful historical subject'),
      deny('CRIMINOLOGY', 'crime-related'),
      deny('CONTRACTLAW', 'legal/adult subject'),
      deny('CORPORATIONLAW', 'legal/adult subject'),
      deny('MATRIMONIALLAW', 'legal/adult subject'),
      deny('PATENTLAW', 'legal/adult subject'),
      deny('JURISPRUDENCE', 'legal/adult subject'),
      deny('HOOFING', 'not school subject'),
      deny('JAMSESSION', 'activity, not school subject'),
      deny('MAMBO', 'dance, not school subject'),
      deny('BYPLAY', 'not school subject'),
      deny('SKIT', 'activity, not school subject'),
      deny('HEROICS', 'not school subject'),
      deny('SYLLOGISTIC', 'obscure logic term'),
      deny('HAMMING', 'obscure coding-theory term'),
      deny('CYBERNETICS', 'advanced/obscure K-8 fit'),
      deny('PRAGMATICS', 'advanced/obscure K-8 fit'),
      deny('METAPHYSICS', 'advanced/obscure K-8 fit'),
      deny('PHILOLOGY', 'advanced/obscure K-8 fit'),
      deny('NEOCLASSICISM', 'art style, not K-8 subject'),
      deny('CLASSICISM', 'art style, not K-8 subject'),
      deny('EPISTEMOLOGY', 'advanced/obscure K-8 fit'),
      deny('DIALECTIC', 'advanced/obscure K-8 fit'),
      deny('LEGALPHILOSOPHY', 'legal/adult subject'),
      deny('MORALPHILOSOPHY', 'advanced/obscure K-8 fit'),
      deny('GEOPOLITICS', 'political/adult subject'),
      deny('METRICS', 'ambiguous/advanced term'),
      deny('ETHNOLOGY', 'advanced/dated social-science term'),
      deny('GROUPTHEORY', 'advanced math topic'),
      deny('MICROECONOMICS', 'advanced subject'),
      deny('REENACTMENT', 'activity, not subject'),
      deny('OVERACTING', 'performance issue, not school subject'),
      deny('LIT', 'abbreviation/unclear subject label'),
      deny('GAMESTUDIES', 'advanced/niche subject'),
    ],
  },
]
