export interface DictCategoryConfig {
  id: string
  name: string
  emoji: string
  group: 'Animals' | 'Plants' | 'Food & Drink' | 'Things & Tools' | 'Science & Nature' | 'People & Activities'
  keywords: string[]
  roots: string[]
  excludeRoots?: string[]
  maxDepth?: number
  minWords?: number
  allowCapitalized?: boolean
  denyTokens?: string[]
}

export const DICT_VERSION = 'oewn2025-scowl2020-1'

export const GLOBAL_EXCLUDE_ROOTS = [
  '04572661-n', // weapon
  '03252323-n', // drug
  '03814104-n', // narcotic
  '07900542-n', // alcoholic drink
  '04449965-n', // tobacco product
  '12928225-n', // tobacco plant
  '05521732-n', // intimate anatomy
  '03417816-n', // execution device
  '03348699-n', // firearm
  '03309675-n', // explosive
  '02869918-n', // bomb
]

export const GLOBAL_DENY_TOKENS = [
  'ALE',
  'AMMO',
  'BOMB',
  'BRANDY',
  'BREAST',
  'BULLET',
  'CANNABIS',
  'CIGAR',
  'CIGARETTE',
  'COCAINE',
  'COCKTAIL',
  'CROTCH',
  'DAGGER',
  'GIN',
  'GROIN',
  'GUN',
  'HEROIN',
  'KNIFE',
  'LIQUOR',
  'MORPHINE',
  'OPIUM',
  'PISTOL',
  'RIFLE',
  'RUM',
  'SWORD',
  'TOBACCO',
  'UTERUS',
  'VODKA',
  'WHISKEY',
  'WINE',
]

export const CATEGORY_CONFIGS: DictCategoryConfig[] = [
  {
    id: 'mammals',
    name: 'Mammals',
    emoji: '🐻',
    group: 'Animals',
    keywords: ['animal', 'mammal', 'wildlife'],
    roots: ['01864419-n'],
    maxDepth: 8,
  },
  {
    id: 'dog-breeds',
    name: 'Dog breeds',
    emoji: '🐶',
    group: 'Animals',
    keywords: ['dog', 'breed', 'pet'],
    roots: ['02086723-n'],
    maxDepth: 7,
    allowCapitalized: true,
    denyTokens: [
      'BARKER',
      'BOWWOW',
      'CUR',
      'DOGGY',
      'DOMESTICDOG',
      'GUNDOG',
      'ATTACKDOG',
      'GUARDDOG',
      'GUIDEDOG',
      'HEARINGDOG',
      'HOUNDDOG',
      'HUNTINGDOG',
      'MUTT',
      'POOCH',
      'POLICEDOG',
      'PUPPY',
      'SHEEPDOG',
      'SHEPHERDDOG',
      'SLEDDOG',
      'SPORTINGDOG',
      'TOY',
      'TOYDOG',
      'WATCHDOG',
      'WORKINGDOG',
    ],
  },
  {
    id: 'cats',
    name: 'Cats',
    emoji: '🐱',
    group: 'Animals',
    keywords: ['cat', 'feline', 'wildcat'],
    roots: ['02123649-n'],
    maxDepth: 7,
  },
  {
    id: 'birds',
    name: 'Birds',
    emoji: '🐦',
    group: 'Animals',
    keywords: ['bird', 'avian', 'feather'],
    roots: ['01505702-n'],
    maxDepth: 7,
  },
  {
    id: 'birds-of-prey',
    name: 'Birds of prey',
    emoji: '🦅',
    group: 'Animals',
    keywords: ['raptor', 'eagle', 'hawk', 'owl'],
    roots: ['01606971-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'fish',
    name: 'Fish',
    emoji: '🐟',
    group: 'Animals',
    keywords: ['fish', 'aquatic', 'ocean'],
    roots: ['02514684-n'],
    maxDepth: 7,
  },
  {
    id: 'reptiles',
    name: 'Reptiles',
    emoji: '🦎',
    group: 'Animals',
    keywords: ['reptile', 'scales', 'cold-blooded'],
    roots: ['01663732-n'],
    maxDepth: 7,
  },
  {
    id: 'snakes',
    name: 'Snakes',
    emoji: '🐍',
    group: 'Animals',
    keywords: ['snake', 'serpent', 'reptile'],
    roots: ['01729333-n'],
    maxDepth: 7,
  },
  {
    id: 'lizards',
    name: 'Lizards',
    emoji: '🦎',
    group: 'Animals',
    keywords: ['lizard', 'reptile', 'gecko'],
    roots: ['01677105-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'amphibians',
    name: 'Amphibians',
    emoji: '🐸',
    group: 'Animals',
    keywords: ['frog', 'toad', 'newt'],
    roots: ['01630065-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'insects',
    name: 'Insects',
    emoji: '🐞',
    group: 'Animals',
    keywords: ['insect', 'bug', 'arthropod'],
    roots: ['02162607-n'],
    maxDepth: 7,
  },
  {
    id: 'butterflies-moths',
    name: 'Butterflies & moths',
    emoji: '🦋',
    group: 'Animals',
    keywords: ['butterfly', 'moth', 'insect'],
    roots: ['02276911-n', '02285853-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'spiders-arachnids',
    name: 'Spiders & arachnids',
    emoji: '🕷️',
    group: 'Animals',
    keywords: ['spider', 'arachnid', 'scorpion'],
    roots: ['01771988-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'crustaceans-shellfish',
    name: 'Crustaceans & shellfish',
    emoji: '🦀',
    group: 'Animals',
    keywords: ['crab', 'lobster', 'mollusk', 'shellfish'],
    roots: ['01977414-n', '01943377-n'],
    maxDepth: 7,
    minWords: 10,
  },
  {
    id: 'dinosaurs',
    name: 'Dinosaurs',
    emoji: '🦖',
    group: 'Animals',
    keywords: ['dinosaur', 'prehistoric', 'fossil'],
    roots: ['01702472-n'],
    maxDepth: 8,
    minWords: 8,
  },
  {
    id: 'trees',
    name: 'Trees',
    emoji: '🌳',
    group: 'Plants',
    keywords: ['tree', 'forest', 'wood'],
    roots: ['13124818-n'],
    maxDepth: 7,
  },
  {
    id: 'flowers',
    name: 'Flowers',
    emoji: '🌸',
    group: 'Plants',
    keywords: ['flower', 'bloom', 'garden'],
    roots: ['11690372-n'],
    maxDepth: 7,
  },
  {
    id: 'herbs-spices',
    name: 'Herbs & spices',
    emoji: '🌿',
    group: 'Plants',
    keywords: ['herb', 'spice', 'seasoning'],
    roots: ['07827392-n', '07828160-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'fruits',
    name: 'Fruits',
    emoji: '🍎',
    group: 'Food & Drink',
    keywords: ['fruit', 'produce', 'sweet'],
    roots: ['07721676-n'],
    maxDepth: 6,
  },
  {
    id: 'berries',
    name: 'Berries',
    emoji: '🫐',
    group: 'Food & Drink',
    keywords: ['berry', 'fruit', 'jam'],
    roots: ['07758680-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    emoji: '🥕',
    group: 'Food & Drink',
    keywords: ['vegetable', 'produce', 'garden'],
    roots: ['07723196-n'],
    maxDepth: 6,
  },
  {
    id: 'nuts',
    name: 'Nuts',
    emoji: '🥜',
    group: 'Food & Drink',
    keywords: ['nut', 'seed', 'snack'],
    roots: ['07753057-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'grains-cereals',
    name: 'Grains & cereals',
    emoji: '🌾',
    group: 'Food & Drink',
    keywords: ['grain', 'cereal', 'wheat', 'rice'],
    roots: ['07818393-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'breads',
    name: 'Breads',
    emoji: '🍞',
    group: 'Food & Drink',
    keywords: ['bread', 'baking', 'loaf'],
    roots: ['07695101-n'],
    maxDepth: 5,
    minWords: 10,
  },
  {
    id: 'cheeses',
    name: 'Cheeses',
    emoji: '🧀',
    group: 'Food & Drink',
    keywords: ['cheese', 'dairy', 'food'],
    roots: ['07866305-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'desserts-sweets',
    name: 'Desserts & sweets',
    emoji: '🍰',
    group: 'Food & Drink',
    keywords: ['dessert', 'sweet', 'treat'],
    roots: ['07625449-n', '07612255-n'],
    maxDepth: 5,
    minWords: 10,
  },
  {
    id: 'candy',
    name: 'Candy',
    emoji: '🍬',
    group: 'Food & Drink',
    keywords: ['candy', 'confection', 'sweet'],
    roots: ['07612936-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'beverages',
    name: 'Beverages',
    emoji: '🥤',
    group: 'Food & Drink',
    keywords: ['drink', 'beverage', 'juice'],
    roots: ['07897775-n'],
    excludeRoots: ['07900542-n'],
    maxDepth: 6,
    minWords: 10,
    denyTokens: ['CAFEROYALE', 'COFFEEROYAL', 'LOVEPOTION', 'NEARBEER', 'PHILTER', 'POTION'],
  },
  {
    id: 'pasta',
    name: 'Pasta',
    emoji: '🍝',
    group: 'Food & Drink',
    keywords: ['pasta', 'noodle', 'food'],
    roots: ['07714660-n', '07879350-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'musical-instruments',
    name: 'Musical instruments',
    emoji: '🎺',
    group: 'Things & Tools',
    keywords: ['music', 'instrument', 'sound'],
    roots: ['03806455-n'],
    maxDepth: 7,
  },
  {
    id: 'tools',
    name: 'Tools',
    emoji: '🛠️',
    group: 'Things & Tools',
    keywords: ['tool', 'workshop', 'implement'],
    roots: ['04459089-n'],
    excludeRoots: ['04572661-n'],
    maxDepth: 7,
    denyTokens: ['BILL', 'DROVE', 'GANG', 'GUTTER', 'STYLE', 'UPSET'],
  },
  {
    id: 'kitchen-utensils',
    name: 'Kitchen utensils',
    emoji: '🍴',
    group: 'Things & Tools',
    keywords: ['kitchen', 'utensil', 'cooking'],
    roots: ['04523967-n', '03158041-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'containers',
    name: 'Containers',
    emoji: '📦',
    group: 'Things & Tools',
    keywords: ['container', 'box', 'holder'],
    roots: ['03099154-n'],
    maxDepth: 6,
  },
  {
    id: 'furniture',
    name: 'Furniture',
    emoji: '🪑',
    group: 'Things & Tools',
    keywords: ['furniture', 'chair', 'table'],
    roots: ['03410635-n'],
    maxDepth: 6,
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    emoji: '🚗',
    group: 'Things & Tools',
    keywords: ['vehicle', 'transport', 'car'],
    roots: ['04531608-n'],
    maxDepth: 6,
  },
  {
    id: 'boats-ships',
    name: 'Boats & ships',
    emoji: '⛵',
    group: 'Things & Tools',
    keywords: ['boat', 'ship', 'watercraft'],
    roots: ['02861626-n', '04201332-n'],
    maxDepth: 6,
  },
  {
    id: 'aircraft',
    name: 'Aircraft',
    emoji: '✈️',
    group: 'Things & Tools',
    keywords: ['aircraft', 'plane', 'flying'],
    roots: ['02689427-n'],
    maxDepth: 6,
  },
  {
    id: 'buildings',
    name: 'Buildings',
    emoji: '🏫',
    group: 'Things & Tools',
    keywords: ['building', 'structure', 'place'],
    roots: ['02916498-n'],
    maxDepth: 6,
  },
  {
    id: 'clothing',
    name: 'Clothing',
    emoji: '👕',
    group: 'Things & Tools',
    keywords: ['clothing', 'clothes', 'wear'],
    roots: ['03055525-n'],
    maxDepth: 6,
  },
  {
    id: 'footwear',
    name: 'Footwear',
    emoji: '👟',
    group: 'Things & Tools',
    keywords: ['footwear', 'shoe', 'boot'],
    roots: ['03385972-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'hats',
    name: 'Hats',
    emoji: '🎩',
    group: 'Things & Tools',
    keywords: ['hat', 'cap', 'headwear'],
    roots: ['03502782-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'fabrics',
    name: 'Fabrics',
    emoji: '🧵',
    group: 'Things & Tools',
    keywords: ['fabric', 'cloth', 'textile'],
    roots: ['03314753-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'toys',
    name: 'Toys',
    emoji: '🧸',
    group: 'Things & Tools',
    keywords: ['toy', 'plaything', 'game'],
    roots: ['03971038-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'games',
    name: 'Games',
    emoji: '🎲',
    group: 'Things & Tools',
    keywords: ['game', 'contest', 'play'],
    roots: ['00456623-n'],
    excludeRoots: ['00524569-n'],
    maxDepth: 6,
    minWords: 10,
    denyTokens: [
      'BLACKJACK',
      'BOODLE',
      'CRAPS',
      'DRAWING',
      'FANTAN',
      'LOTTERY',
      'PILLOWFIGHT',
      'POSTOFFICE',
      'RAFFLE',
      'ROULETTE',
      'SWEEPSTAKES',
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    group: 'People & Activities',
    keywords: ['sport', 'athletics', 'competition'],
    roots: ['00524569-n'],
    maxDepth: 6,
    denyTokens: ['COURSING', 'FIGHT', 'HUNT', 'HUNTING'],
  },
  {
    id: 'dances',
    name: 'Dances',
    emoji: '💃',
    group: 'People & Activities',
    keywords: ['dance', 'movement', 'music'],
    roots: ['00429255-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'occupations',
    name: 'Occupations',
    emoji: '👩‍🏫',
    group: 'People & Activities',
    keywords: ['job', 'worker', 'career'],
    roots: ['09655706-n', '10499838-n', '10073616-n'],
    maxDepth: 5,
    denyTokens: [
      'ACCOMPLICE',
      'BEATER',
      'CHAR',
      'DOMESTIC',
      'FAMILIAR',
      'GENTLEMAN',
      'GUTTER',
      'HANGOVER',
      'HELP',
      'HIRE',
      'INDEPENDENT',
      'INSTRUMENT',
      'LOVELY',
      'MAN',
      'PRIVATE',
      'RECRUIT',
      'SCAB',
      'SERVANT',
      'SLAVE',
      'SOLDIER',
      'SUBSIDIARY',
      'SUPPORTER',
      'TEMPORARY',
      'VET',
      'VOLUNTARY',
    ],
  },
  {
    id: 'family-relatives',
    name: 'Family relatives',
    emoji: '👪',
    group: 'People & Activities',
    keywords: ['family', 'relative', 'relation'],
    roots: ['10255246-n'],
    maxDepth: 4,
    minWords: 8,
    denyTokens: ['BIGAMIST', 'CHERUB', 'HOUSEWIFE', 'MATRON', 'PATRIARCH'],
  },
  {
    id: 'body-parts',
    name: 'Body parts',
    emoji: '🖐️',
    group: 'Science & Nature',
    keywords: ['body', 'anatomy', 'part'],
    roots: ['05227735-n'],
    excludeRoots: ['05521732-n'],
    maxDepth: 6,
    denyTokens: ['BREAST', 'BUST', 'CLEAVAGE', 'COBBLERS', 'CROTCH', 'DUG', 'EGG', 'GROIN', 'TEAT', 'UDDER', 'UTERUS'],
  },
  {
    id: 'bones',
    name: 'Bones',
    emoji: '🦴',
    group: 'Science & Nature',
    keywords: ['bone', 'skeleton', 'anatomy'],
    roots: ['05277400-n'],
    maxDepth: 6,
    minWords: 8,
  },
  {
    id: 'gemstones',
    name: 'Gemstones',
    emoji: '💎',
    group: 'Science & Nature',
    keywords: ['gem', 'gemstone', 'jewel'],
    roots: ['14723913-n'],
    maxDepth: 5,
    minWords: 8,
  },
  {
    id: 'minerals',
    name: 'Minerals',
    emoji: '🔬',
    group: 'Science & Nature',
    keywords: ['mineral', 'crystal', 'geology'],
    roots: ['14686753-n'],
    maxDepth: 5,
  },
  {
    id: 'rocks',
    name: 'Rocks',
    emoji: '🪨',
    group: 'Science & Nature',
    keywords: ['rock', 'stone', 'geology'],
    roots: ['14720954-n', '09438954-n'],
    maxDepth: 5,
    minWords: 10,
    denyTokens: ['MOLD'],
  },
  {
    id: 'metals-elements',
    name: 'Metals & elements',
    emoji: '⚗️',
    group: 'Science & Nature',
    keywords: ['metal', 'element', 'chemistry'],
    roots: ['14647071-n', '14649636-n'],
    maxDepth: 4,
    minWords: 10,
  },
  {
    id: 'colors',
    name: 'Colors',
    emoji: '🎨',
    group: 'Science & Nature',
    keywords: ['color', 'colour', 'hue'],
    roots: ['04963771-n'],
    excludeRoots: ['04984219-n'],
    maxDepth: 5,
    minWords: 10,
  },
  {
    id: 'geometric-shapes',
    name: 'Geometric shapes',
    emoji: '🔷',
    group: 'Science & Nature',
    keywords: ['shape', 'geometry', 'figure'],
    roots: ['13885789-n', '13888765-n', '13896141-n', '13906542-n', '13921893-n', '13895231-n', '13887919-n', '13937623-n'],
    maxDepth: 5,
    minWords: 10,
    denyTokens: ['BOX', 'BUST', 'MOBILE', 'MODELING', 'MOLD', 'RELIEF', 'TERM', 'TREE', 'TREEDIAGRAM'],
  },
  {
    id: 'weather-phenomena',
    name: 'Weather phenomena',
    emoji: '🌦️',
    group: 'Science & Nature',
    keywords: ['weather', 'storm', 'cloud'],
    roots: ['11545095-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'bodies-of-water',
    name: 'Bodies of water',
    emoji: '🌊',
    group: 'Science & Nature',
    keywords: ['water', 'river', 'lake', 'ocean'],
    roots: ['09248053-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'landforms',
    name: 'Landforms',
    emoji: '⛰️',
    group: 'Science & Nature',
    keywords: ['landform', 'geology', 'mountain'],
    roots: ['09310874-n'],
    maxDepth: 6,
    minWords: 10,
  },
  {
    id: 'school-subjects',
    name: 'School subjects',
    emoji: '📚',
    group: 'Science & Nature',
    keywords: ['school', 'subject', 'discipline'],
    roots: ['06005806-n'],
    maxDepth: 4,
    minWords: 10,
    denyTokens: ['BUSINESS', 'MEMORY', 'METHOD', 'MODELING', 'OBJECT', 'PHRASE', 'PLAYING', 'STRATEGY', 'TACTICS', 'VARIATION'],
  },
]
